export const expensesCategoriesEnum = [
  "Housing",
  "Utilities",
  "Groceries",
  "Transportation",
  "Insurance",
  "Healthcare",
  "Debt Payments",
  "Savings",
  "Entertainment",
  "Dining Out",
  "Education",
  "Personal Care",
  "Clothing",
  "Gifts & Donations",
  "Travel",
  "Childcare",
  "Miscellaneous",
]

export const incomeCategoriesEnum = [
  "Salary",
  "Business",
  "Freelancing",
  "Investments",
  "Rental Income",
  "Bonuses",
  "Interest",
  "Pension",
  "Other",
]
